name: Build Android APK

on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up JDK 11
              uses: actions/setup-java@v3
              with:
                  distribution: 'temurin'
                  java-version: '11'

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.11"

            - name: Setup Android SDK
              uses: android-actions/setup-android@v3

            - name: Install system dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y python3-pip build-essential git zip unzip wget curl
                  sudo apt-get install -y python3-setuptools python3-dev libffi-dev libssl-dev

            - name: Install Python dependencies
              run: |
                  pip install --upgrade pip
                  pip install cython==0.29.33
                  pip install buildozer
                  pip install python-for-android

            - name: Accept Android licenses
              run: |
                  yes | sdkmanager --licenses

            - name: Install Android components
              run: |
                  sdkmanager "platform-tools" "platforms;android-29" "build-tools;29.0.3" "ndk;21.4.7075529"

            - name: Verify Android Setup
              run: |
                  echo "=== Android SDK Setup Verification ==="
                  echo "ANDROID_HOME: $ANDROID_HOME"
                  echo "ANDROID_SDK_ROOT: $ANDROID_SDK_ROOT"
                  echo ""
                  echo "Looking for AIDL binary:"
                  find $ANDROID_HOME -name "aidl" -type f 2>/dev/null || echo "AIDL not found!"
                  echo ""
                  echo "Testing AIDL command:"
                  which aidl || echo "AIDL not in PATH"
                  $ANDROID_HOME/build-tools/29.0.3/aidl --help 2>/dev/null | head -3 || echo "Cannot run AIDL from build-tools"

            - name: Build APK
              run: |
                  echo "=== Starting APK Build ==="
                  export PATH=$PATH:$ANDROID_HOME/build-tools/29.0.3
                  buildozer android debug

            - name: Find APK
              run: |
                  find . -name "*.apk" -type f
                  ls -la bin/ || echo "No bin directory"

            - name: Upload APK
              uses: actions/upload-artifact@v4
              with:
                  name: remote-controller-apk
                  path: "bin/*.apk"
                  if-no-files-found: error
