name: Build Android APK

on:
    push:
        branches: [main, master]
    pull_request:
        branches: [main, master]
    workflow_dispatch:

jobs:
    build-android:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.10"

            - name: Setup Java JDK
              uses: actions/setup-java@v4
              with:
                  distribution: 'temurin'
                  java-version: '17'

            - name: Setup Android SDK
              uses: android-actions/setup-android@v3
              with:
                  api-level: 33
                  build-tools: 33.0.0
                  ndk-version: 25.2.9519653

            - name: Install system dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y build-essential git unzip python3-setuptools
                  sudo apt-get install -y libtool libffi-dev libssl-dev python3-dev libltdl-dev
                  sudo apt-get install -y libncurses5-dev zlib1g-dev libbz2-dev libsqlite3-dev
                  sudo apt-get install -y libgdbm-dev libdb-dev libreadline-dev libpcap-dev tk-dev

            - name: Cache buildozer global directory
              uses: actions/cache@v3
              with:
                  path: .buildozer_global
                  key: buildozer-global-${{ hashFiles('buildozer.spec') }}

            - name: Cache buildozer directory
              uses: actions/cache@v3
              with:
                  path: .buildozer
                  key: buildozer-${{ hashFiles('buildozer.spec') }}

            - name: Install Python dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install buildozer cython==0.29.33

            - name: Build Android APK
              run: |
                  export ANDROID_SDK_ROOT=$ANDROID_HOME
                  export PATH=$PATH:$ANDROID_HOME/build-tools/33.0.0
                  yes | buildozer android debug

            - name: Upload APK
              uses: actions/upload-artifact@v4
              with:
                  name: android-apk
                  path: bin/*.apk
