name: Build Android APK

on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                  distribution: 'temurin'
                  java-version: '17'

            - name: Setup Android SDK
              uses: android-actions/setup-android@v3
              env:
                  SKIP_JDK_VERSION_CHECK: true
                  JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.16-8/x64

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.11"

            - name: Install system dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y python3-pip build-essential git zip unzip wget curl
                  sudo apt-get install -y python3-setuptools python3-dev libffi-dev libssl-dev

            - name: Install Python dependencies
              run: |
                  pip install --upgrade pip
                  pip install cython==0.29.33
                  pip install python-for-android

            - name: Accept Android licenses
              run: yes | sdkmanager --licenses

            - name: Install Android components (auto-detect latest API)
              run: |
                  export JAVA_HOME=/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.16-8/x64
                  export PATH=$JAVA_HOME/bin:$PATH

                  # Always install platform-tools + NDK
                  sdkmanager "platform-tools" "ndk;25.2.9519653"

                  # Detect latest platform + build-tools
                  LATEST_API=$(sdkmanager --list | grep "platforms;android-" | grep -oE "[0-9]+" | sort -n | tail -1)
                  echo "Using Android API level: $LATEST_API"
                  sdkmanager "platforms;android-$LATEST_API" "build-tools;$LATEST_API.0.0"

                  echo "ANDROIDAPI=$LATEST_API" >> $GITHUB_ENV

            - name: Build APK with Python-for-Android directly
              run: |
                  echo "=== Building APK with P4A ==="

                  export JAVA_HOME=/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.16-8/x64
                  export PATH=$JAVA_HOME/bin:$PATH

                  export ANDROID_HOME=/usr/local/lib/android/sdk
                  export ANDROID_SDK_ROOT=/usr/local/lib/android/sdk
                  export ANDROIDNDK=$ANDROID_HOME/ndk/25.2.9519653
                  export PATH=$ANDROID_HOME/build-tools/${ANDROIDAPI}.0.0:$ANDROID_HOME/platform-tools:$PATH

                  echo "JAVA_HOME=$JAVA_HOME"
                  echo "ANDROID_HOME=$ANDROID_HOME"
                  echo "ANDROIDNDK=$ANDROIDNDK"
                  echo "ANDROIDAPI=$ANDROIDAPI"

                  p4a apk \
                    --private . \
                    --package=com.tarbunny.remote_controller \
                    --name="Remote Controller" \
                    --version=1.0 \
                    --bootstrap=sdl2 \
                    --requirements=python3,kivy,requests,urllib3 \
                    --permissions=INTERNET,ACCESS_NETWORK_STATE \
                    --arch=arm64-v8a \
                    --release \
                    --sdk-dir=$ANDROID_HOME \
                    --ndk-dir=$ANDROIDNDK \
                    --android-api=$ANDROIDAPI \
                    --ndk-api=21

            - name: Find APK
              run: |
                  find . -name "*.apk" -type f
                  ls -la bin/ || echo "No bin directory"

            - name: Upload APK
              uses: actions/upload-artifact@v4
              with:
                  name: remote-controller-apk
                  path: "bin/*.apk"
                  if-no-files-found: error
