name: Build Android APK

on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.11"

            - name: Install system dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y python3-pip build-essential git zip unzip openjdk-11-jdk wget curl
                  sudo apt-get install -y python3-setuptools python3-dev libffi-dev libssl-dev

            - name: Install Python dependencies
              run: |
                  pip install --upgrade pip
                  pip install cython==0.29.33
                  pip install buildozer
                  pip install python-for-android

            - name: Setup Android SDK
              run: |
                  mkdir -p /home/runner/android-sdk/cmdline-tools
                  cd /home/runner
                  wget -q https://dl.google.com/android/repository/commandlinetools-linux-6514223_latest.zip
                  unzip -q commandlinetools-linux-6514223_latest.zip
                  mv tools /home/runner/android-sdk/cmdline-tools/latest

                  # Accept licenses
                  mkdir -p /home/runner/android-sdk/licenses
                  echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > /home/runner/android-sdk/licenses/android-sdk-license
                  echo "d975f751698a77b662f1254ddbeed3901e976f5a" > /home/runner/android-sdk/licenses/intel-android-extra-license

                  # Set environment variables
                  echo "ANDROID_HOME=/home/runner/android-sdk" >> $GITHUB_ENV
                  echo "ANDROID_SDK_ROOT=/home/runner/android-sdk" >> $GITHUB_ENV
                  echo "/home/runner/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH

                  # Install required packages
                  /home/runner/android-sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.0"

            - name: Build APK
              run: |
                  buildozer android debug

            - name: Find APK
              run: |
                  find . -name "*.apk" -type f
                  ls -la bin/ || echo "No bin directory"

            - name: Upload APK
              uses: actions/upload-artifact@v4
              with:
                  name: remote-controller-apk
                  path: "bin/*.apk"
                  if-no-files-found: error
