- name: Install Android components
  run: |
      export JAVA_HOME=/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.16-8/x64
      export PATH=$JAVA_HOME/bin:$PATH
      sdkmanager "platform-tools" "platforms;android-35" "build-tools;35.0.0" "ndk;25.2.9519653"

- name: Build APK with Python-for-Android directly (FUCK BUILDOZER!)
  run: |
      echo "=== FUCK BUILDOZER - USING P4A DIRECTLY ==="
      
      # Java 17 for Android SDK tools
      export JAVA_HOME=/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.16-8/x64
      export PATH=$JAVA_HOME/bin:$PATH
      
      # Android SDK/NDK setup
      export ANDROID_HOME=/usr/local/lib/android/sdk
      export ANDROID_SDK_ROOT=/usr/local/lib/android/sdk
      export ANDROIDAPI=35
      export ANDROIDNDK=/usr/local/lib/android/sdk/ndk/25.2.9519653
      export PATH=$ANDROID_HOME/build-tools/35.0.0:$ANDROID_HOME/platform-tools:$PATH
      
      # Build APK
      p4a apk \
        --private . \
        --package=com.tarbunny.remote_controller \
        --name="Remote Controller" \
        --version=1.0 \
        --bootstrap=sdl2 \
        --requirements=python3,kivy,requests,urllib3 \
        --permissions=INTERNET,ACCESS_NETWORK_STATE \
        --arch=arm64-v8a \
        --release \
        --sdk-dir=$ANDROID_HOME \
        --ndk-dir=$ANDROIDNDK \
        --android-api=$ANDROIDAPI \
        --ndk-api=21
