name: Build Android APK

on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up JDK 11
              uses: actions/setup-java@v3
              with:
                  distribution: 'temurin'
                  java-version: '11'

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.11"

            - name: Setup Android SDK
              uses: android-actions/setup-android@v3
              env:
                  SKIP_JDK_VERSION_CHECK: true

            - name: Install system dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y python3-pip build-essential git zip unzip wget curl
                  sudo apt-get install -y python3-setuptools python3-dev libffi-dev libssl-dev

            - name: Install Python dependencies
              run: |
                  pip install --upgrade pip
                  pip install cython==0.29.33
                  pip install buildozer
                  pip install python-for-android

            - name: Accept Android licenses
              run: |
                  yes | sdkmanager --licenses

            - name: Install Android components
              run: |
                  sdkmanager "platform-tools" "platforms;android-29" "build-tools;29.0.3" "ndk;21.4.7075529"

            - name: Verify Android Setup
              run: |
                  echo "=== Android SDK Setup Verification ==="
                  echo "ANDROID_HOME: $ANDROID_HOME"
                  echo "ANDROID_SDK_ROOT: $ANDROID_SDK_ROOT"
                  echo ""
                  echo "Looking for AIDL binary:"
                  find $ANDROID_HOME -name "aidl" -type f 2>/dev/null || echo "AIDL not found!"
                  echo ""
                  echo "Testing AIDL command:"
                  which aidl || echo "AIDL not in PATH"
                  $ANDROID_HOME/build-tools/29.0.3/aidl --help 2>/dev/null | head -3 || echo "Cannot run AIDL from build-tools"

            - name: Build APK
              run: |
                  echo "=== Starting APK Build ==="
                  
                  # Set Java 11 for compatibility with older Android SDK tools
                  export JAVA_HOME=/usr/lib/jvm/temurin-11-jdk-amd64
                  export PATH=$JAVA_HOME/bin:$PATH
                  
                  # Remove buildozer's cache to force fresh setup
                  rm -rf /home/runner/.buildozer/
                  
                  # Set environment variables that buildozer respects
                  export ANDROID_HOME=/usr/local/lib/android/sdk
                  export ANDROID_SDK_ROOT=/usr/local/lib/android/sdk
                  export ANDROIDSDK=/usr/local/lib/android/sdk
                  export ANDROIDNDK=/usr/local/lib/android/sdk/ndk/21.4.7075529
                  export ANDROIDAPI=29
                  export ANDROIDNDKVER=r21e
                  
                  # Add Android tools to PATH
                  export PATH=$PATH:/usr/local/lib/android/sdk/build-tools/29.0.3
                  export PATH=$PATH:/usr/local/lib/android/sdk/platform-tools
                  export PATH=$PATH:/usr/local/lib/android/sdk/tools/bin
                  
                  echo "=== Environment Check ==="
                  echo "JAVA_HOME: $JAVA_HOME"
                  echo "ANDROID_HOME: $ANDROID_HOME"
                  java -version
                  which aidl
                  aidl --help | head -3
                  
                  # Build with verbose output
                  buildozer android debug --verbose

            - name: Find APK
              run: |
                  find . -name "*.apk" -type f
                  ls -la bin/ || echo "No bin directory"

            - name: Upload APK
              uses: actions/upload-artifact@v4
              with:
                  name: remote-controller-apk
                  path: "bin/*.apk"
                  if-no-files-found: error
